"use client";

import { useState } from "react";
import { ApiErrorState } from "@/components/api-state";
import type { Dictionary } from "@/i18n/dictionaries";
import { useI18n } from "@/i18n/locale-provider";
import { formatNumber, interpolate, type Locale } from "@/i18n/locale";
import type { ApiFailure } from "@/lib/api";
import { createAlertRule, deleteAlertRule, dispatchAlertRule, listAlertRules, setAlertRuleEnabled, type AlertRule } from "@/lib/alert-rules";

type Notice = (dictionary: Dictionary, locale: Locale) => string;

export function AlertRulesPanel() {
  const { locale, dictionary } = useI18n();
  const [rules, setRules] = useState<AlertRule[]>([]);
  const [name, setName] = useState(""); const [companyQuery, setCompanyQuery] = useState(""); const [skillQuery, setSkillQuery] = useState("");
  const [error, setError] = useState<ApiFailure | null>(null); const [notice, setNotice] = useState<Notice | null>(null); const [busy, setBusy] = useState(false);

  async function loadRules() { setBusy(true); setError(null); setNotice(null); const result = await listAlertRules(); if (result.kind === "error") setError(result); else setRules(result.value.data); setBusy(false); }
  async function createRule(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!name.trim() || (!companyQuery.trim() && !skillQuery.trim())) { setError({ kind: "error", status: 422, code: "alert_rule_invalid", message: dictionary.alerts.validation }); return; } setBusy(true); setError(null); setNotice(null); const result = await createAlertRule({ name: name.trim(), companyQuery: companyQuery.trim() || undefined, skillQuery: skillQuery.trim() || undefined, enabled: true }); if (result.kind === "error") setError(result); else { setRules((current) => [result.value.data, ...current]); setName(""); setCompanyQuery(""); setSkillQuery(""); setNotice(() => (messages: Dictionary) => messages.alerts.created); } setBusy(false); }
  async function toggleRule(rule: AlertRule) { setBusy(true); setError(null); setNotice(null); const result = await setAlertRuleEnabled(rule.id, !rule.enabled); if (result.kind === "error") setError(result); else setRules((current) => current.map((item) => item.id === rule.id ? result.value.data : item)); setBusy(false); }
  async function removeRule(rule: AlertRule) { if (!window.confirm(interpolate(dictionary.alerts.deleteConfirm, { name: rule.name }))) return; setBusy(true); setError(null); setNotice(null); const result = await deleteAlertRule(rule.id); if (result.kind === "error") setError(result); else { setRules((current) => current.filter((item) => item.id !== rule.id)); setNotice(() => (messages: Dictionary) => messages.alerts.deleted); } setBusy(false); }
  async function dispatchRule(rule: AlertRule) { setBusy(true); setError(null); setNotice(null); const result = await dispatchAlertRule(rule.id); if (result.kind === "error") setError(result); else { const summary = result.value.data; setNotice(() => (messages: Dictionary, currentLocale: Locale) => interpolate(messages.alerts.dispatchSummary, { considered: formatNumber(summary.consideredJobs, currentLocale), sent: formatNumber(summary.sentDeliveries, currentLocale), skipped: formatNumber(summary.skippedDeliveries, currentLocale) })); } setBusy(false); }

  return <div className="workflow-layout">
    <section className="content-section alert-intro"><div className="section-heading"><div><p className="eyebrow">{dictionary.alerts.scopeEyebrow}</p><h2>{dictionary.alerts.scopeTitle}</h2></div><span className="channel-badge">{dictionary.alerts.channelNote}</span></div><p>{dictionary.alerts.scopeBody}</p></section>
    <section className="content-section"><div className="section-heading"><div><p className="eyebrow">{dictionary.alerts.sessionEyebrow}</p><h2>{dictionary.alerts.manage}</h2></div><button type="button" onClick={() => void loadRules()} disabled={busy}>{busy ? dictionary.common.loading : dictionary.alerts.loadRules}</button></div><p className="field-help">{dictionary.alerts.sessionBody}</p></section>
    <section className="content-section"><div className="section-heading"><div><p className="eyebrow">{dictionary.alerts.builderEyebrow}</p><h2>{dictionary.alerts.create}</h2></div><span>{dictionary.alerts.oneFilter}</span></div><form className="rule-builder filter-form" onSubmit={createRule}><label htmlFor="alert-name">{dictionary.alerts.name}<input id="alert-name" value={name} onChange={(event) => setName(event.target.value)} maxLength={100} placeholder={dictionary.alerts.namePlaceholder} /></label><label htmlFor="alert-company">{dictionary.alerts.company}<input id="alert-company" value={companyQuery} onChange={(event) => setCompanyQuery(event.target.value)} maxLength={200} placeholder={dictionary.alerts.companyPlaceholder} /></label><label htmlFor="alert-skill">{dictionary.alerts.skill}<input id="alert-skill" value={skillQuery} onChange={(event) => setSkillQuery(event.target.value)} maxLength={100} placeholder={dictionary.alerts.skillPlaceholder} /></label><button className="button-primary" type="submit" disabled={busy}>{dictionary.alerts.createRule}</button></form></section>
    {error ? <ApiErrorState error={error} /> : null}{notice ? <p className="status-message" role="status">{notice(dictionary, locale)}</p> : null}
    <section className="content-section" aria-live="polite"><div className="section-heading"><div><p className="eyebrow">{dictionary.alerts.ownerRules}</p><h2>{formatNumber(rules.length, locale)} {dictionary.alerts.configured}</h2></div>{rules.length ? <span>{dictionary.common.newestFirst}</span> : null}</div>{rules.length ? <div className="match-list">{rules.map((rule) => <article className="match-card rule-card" key={rule.id}><div className="section-heading"><div><p className="eyebrow"><span className="channel-badge">{rule.channel}</span> · {rule.enabled ? dictionary.status.enabled : dictionary.status.paused}</p><h3>{rule.name}</h3><p>{[rule.companyQuery && `${dictionary.alerts.companyPrefix}: ${rule.companyQuery}`, rule.skillQuery && `${dictionary.alerts.skillPrefix}: ${rule.skillQuery}`].filter(Boolean).join(" · ")}</p></div><div className="rule-actions"><button type="button" onClick={() => void dispatchRule(rule)} disabled={busy || !rule.enabled}>{dictionary.alerts.dispatch}</button> <button type="button" onClick={() => void toggleRule(rule)} disabled={busy}>{rule.enabled ? dictionary.common.pause : dictionary.common.enable}</button> <button className="danger-button" type="button" onClick={() => void removeRule(rule)} disabled={busy}>{dictionary.alerts.deleteRule}</button></div></div></article>)}</div> : <div className="api-state empty-state"><strong>{dictionary.alerts.noRules}</strong><p>{dictionary.alerts.noRulesBody}</p></div>}</section>
  </div>;
}
