"use client";

import { useState } from "react";
import { ApiErrorState } from "@/components/api-state";
import type { ApiFailure } from "@/lib/api";
import { createAlertRule, deleteAlertRule, dispatchAlertRule, listAlertRules, setAlertRuleEnabled, type AlertRule } from "@/lib/alert-rules";

export function AlertRulesPanel() {
  const [ownerToken, setOwnerToken] = useState(""); const [rules, setRules] = useState<AlertRule[]>([]);
  const [name, setName] = useState(""); const [companyQuery, setCompanyQuery] = useState(""); const [skillQuery, setSkillQuery] = useState("");
  const [error, setError] = useState<ApiFailure | null>(null); const [notice, setNotice] = useState<string | null>(null); const [busy, setBusy] = useState(false);

  async function loadRules() { if (!ownerToken.trim()) { setError({ kind: "error", status: 403, code: "alert_owner_invalid", message: "Enter the local owner token to continue." }); return; } setBusy(true); setError(null); setNotice(null); const result = await listAlertRules(ownerToken.trim()); if (result.kind === "error") setError(result); else setRules(result.value.data); setBusy(false); }
  async function createRule(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!name.trim() || (!companyQuery.trim() && !skillQuery.trim())) { setError({ kind: "error", status: 422, code: "alert_rule_invalid", message: "Add a name and at least one company or skill filter." }); return; } setBusy(true); setError(null); setNotice(null); const result = await createAlertRule(ownerToken.trim(), { name: name.trim(), companyQuery: companyQuery.trim() || undefined, skillQuery: skillQuery.trim() || undefined, enabled: true }); if (result.kind === "error") setError(result); else { setRules((current) => [result.value.data, ...current]); setName(""); setCompanyQuery(""); setSkillQuery(""); setNotice("Alert rule created. Dispatch stays bounded and protected."); } setBusy(false); }
  async function toggleRule(rule: AlertRule) { setBusy(true); setError(null); setNotice(null); const result = await setAlertRuleEnabled(ownerToken.trim(), rule.id, !rule.enabled); if (result.kind === "error") setError(result); else setRules((current) => current.map((item) => item.id === rule.id ? result.value.data : item)); setBusy(false); }
  async function removeRule(rule: AlertRule) { if (!window.confirm(`Delete alert rule ${rule.name}?`)) return; setBusy(true); setError(null); setNotice(null); const result = await deleteAlertRule(ownerToken.trim(), rule.id); if (result.kind === "error") setError(result); else { setRules((current) => current.filter((item) => item.id !== rule.id)); setNotice("Alert rule and delivery history deleted."); } setBusy(false); }
  async function dispatchRule(rule: AlertRule) { setBusy(true); setError(null); setNotice(null); const result = await dispatchAlertRule(ownerToken.trim(), rule.id); if (result.kind === "error") setError(result); else setNotice(`Dispatch checked ${result.value.data.consideredJobs} jobs: ${result.value.data.sentDeliveries} sent, ${result.value.data.skippedDeliveries} replay-safe skips.`); setBusy(false); }

  return <>
    <section className="content-section"><div className="section-heading"><div><p className="eyebrow">Local and protected</p><h2>Watch the market without spamming it.</h2></div><span>Discord connector · no webhook in browser</span></div><p>Create a literal company or skill rule. The server owns the webhook, keeps delivery history, and prevents replay duplicates. Match-threshold rules remain available through the protected API when a profile is active.</p></section>
    <section className="content-section"><form className="filter-form" onSubmit={(event) => { event.preventDefault(); void loadRules(); }}><label htmlFor="alert-owner-token">Owner token<input id="alert-owner-token" type="password" autoComplete="off" minLength={32} maxLength={128} value={ownerToken} onChange={(event) => setOwnerToken(event.target.value)} /></label><button type="submit" disabled={busy}>{busy ? "Loading..." : "Load my rules"}</button></form><p className="field-help">The token stays in this tab&apos;s memory. It is never written to localStorage, cookies, or the URL.</p></section>
    <section className="content-section"><div className="section-heading"><div><p className="eyebrow">Rule builder</p><h2>Create an alert</h2></div><span>At least one filter</span></div><form className="filter-form" onSubmit={createRule}><label htmlFor="alert-name">Rule name<input id="alert-name" value={name} onChange={(event) => setName(event.target.value)} maxLength={100} placeholder="Backend roles" /></label><label htmlFor="alert-company">Company contains<input id="alert-company" value={companyQuery} onChange={(event) => setCompanyQuery(event.target.value)} maxLength={200} placeholder="Example" /></label><label htmlFor="alert-skill">Skill contains<input id="alert-skill" value={skillQuery} onChange={(event) => setSkillQuery(event.target.value)} maxLength={100} placeholder="Python" /></label><button type="submit" disabled={busy || !ownerToken.trim()}>Create rule</button></form></section>
    {error ? <ApiErrorState error={error} /> : null}{notice ? <p className="status-message" role="status">{notice}</p> : null}
    <section className="content-section" aria-live="polite"><div className="section-heading"><div><p className="eyebrow">Owner rules</p><h2>{rules.length} configured</h2></div>{rules.length ? <span>Newest first</span> : null}</div>{rules.length ? <div className="match-list">{rules.map((rule) => <article className="match-card" key={rule.id}><div className="section-heading"><div><p className="eyebrow">{rule.channel} · {rule.enabled ? "enabled" : "paused"}</p><h3>{rule.name}</h3><p>{[rule.companyQuery && `Company: ${rule.companyQuery}`, rule.skillQuery && `Skill: ${rule.skillQuery}`].filter(Boolean).join(" · ")}</p></div><div><button type="button" onClick={() => void dispatchRule(rule)} disabled={busy || !rule.enabled}>Dispatch up to 5</button> <button type="button" onClick={() => void toggleRule(rule)} disabled={busy}>{rule.enabled ? "Pause" : "Enable"}</button> <button className="danger-button" type="button" onClick={() => void removeRule(rule)} disabled={busy}>Delete</button></div></div></article>)}</div> : <div className="api-state empty-state"><strong>No rules loaded</strong><p>Enter your protected owner token, then create a company or skill watch.</p></div>}</section>
  </>;
}
